/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: verushash.i

package verushash

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



#cgo LDFLAGS: -L${SRCDIR}  -l:libverushash.a -lsodium

typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
extern void _wrap_Swig_free_verushash_c89415b43d900127(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_verushash_c89415b43d900127(swig_intgo arg1);
extern void _wrap_Verushash_initialized_set_verushash_c89415b43d900127(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_Verushash_initialized_get_verushash_c89415b43d900127(uintptr_t arg1);
extern void _wrap_Verushash_initialize_verushash_c89415b43d900127(uintptr_t arg1);
extern void _wrap_Verushash_verushash_verushash_c89415b43d900127(uintptr_t arg1, swig_type_1 arg2, swig_intgo arg3, swig_type_2 arg4);
extern void _wrap_Verushash_verushash_v2_verushash_c89415b43d900127(uintptr_t arg1, swig_voidp arg2, swig_intgo arg3, swig_type_3 arg4);
extern void _wrap_Verushash_verushash_v2b_verushash_c89415b43d900127(uintptr_t arg1, swig_voidp arg2, swig_intgo arg3, swig_type_4 arg4);
extern void _wrap_Verushash_verushash_v2b1_verushash_c89415b43d900127(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3, swig_type_5 arg4);
extern void _wrap_Verushash_verushash_v2b2_verushash_c89415b43d900127(uintptr_t arg1, uintptr_t arg2, swig_type_6 arg3);
extern uintptr_t _wrap_new_Verushash_verushash_c89415b43d900127(void);
extern void _wrap_delete_Verushash_verushash_c89415b43d900127(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_verushash_c89415b43d900127(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_verushash_c89415b43d900127(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrVerushash uintptr

func (p SwigcptrVerushash) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVerushash) SwigIsVerushash() {
}

func (arg1 SwigcptrVerushash) SetInitialized(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Verushash_initialized_set_verushash_c89415b43d900127(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrVerushash) GetInitialized() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Verushash_initialized_get_verushash_c89415b43d900127(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVerushash) Initialize() {
	_swig_i_0 := arg1
	C._wrap_Verushash_initialize_verushash_c89415b43d900127(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrVerushash) Verushash(arg2 string, arg3 int, arg4 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_Verushash_verushash_verushash_c89415b43d900127(C.uintptr_t(_swig_i_0), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
}

func (arg1 SwigcptrVerushash) Verushash_v2(arg2 *byte, arg3 int, arg4 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_Verushash_verushash_v2_verushash_c89415b43d900127(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_intgo(_swig_i_2), *(*C.swig_type_3)(unsafe.Pointer(&_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
}

func (arg1 SwigcptrVerushash) Verushash_v2b(arg2 *byte, arg3 int, arg4 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_Verushash_verushash_v2b_verushash_c89415b43d900127(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_intgo(_swig_i_2), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
}

func (arg1 SwigcptrVerushash) Verushash_v2b1(arg2 Std_string, arg3 int, arg4 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_Verushash_verushash_v2b1_verushash_c89415b43d900127(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2), *(*C.swig_type_5)(unsafe.Pointer(&_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
}

func (arg1 SwigcptrVerushash) Verushash_v2b2(arg2 Std_string, arg3 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_Verushash_verushash_v2b2_verushash_c89415b43d900127(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func NewVerushash() (_swig_ret Verushash) {
	var swig_r Verushash
	swig_r = (Verushash)(SwigcptrVerushash(C._wrap_new_Verushash_verushash_c89415b43d900127()))
	return swig_r
}

func DeleteVerushash(arg1 Verushash) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Verushash_verushash_c89415b43d900127(C.uintptr_t(_swig_i_0))
}

type Verushash interface {
	Swigcptr() uintptr
	SwigIsVerushash()
	SetInitialized(arg2 bool)
	GetInitialized() (_swig_ret bool)
	Initialize()
	Verushash(arg2 string, arg3 int, arg4 string)
	Verushash_v2(arg2 *byte, arg3 int, arg4 string)
	Verushash_v2b(arg2 *byte, arg3 int, arg4 string)
	Verushash_v2b1(arg2 Std_string, arg3 int, arg4 string)
	Verushash_v2b2(arg2 Std_string, arg3 string)
}


type SwigcptrStd_string uintptr
type Std_string interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_string) Swigcptr() uintptr {
	return uintptr(p)
}

